upstream node_cluster {
    server node1:3001;
    server node2:3001;
    server node3:3001;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://node_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}